services:
  app:
    build: ./website
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db


  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - /home/ubuntu/intelligent-traffic-lights/code_EC2/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /home/ubuntu/intelligent-traffic-lights/code_EC2/data:/var/lib/mysql