version: '3'

services:
  app:
    build: ./website
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: db_password
      MYSQL_DATABASE: semaphores
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "32000:3306"
    volumes:
      - /database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /data:/var/lib/mysql