-- MySQL Script generated by MySQL Workbench
-- Thu Nov 30 01:52:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_smart_traffic_light
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_smart_traffic_light` ;

-- -----------------------------------------------------
-- Schema db_smart_traffic_light
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_smart_traffic_light` DEFAULT CHARACTER SET utf8 ;
USE `db_smart_traffic_light` ;

-- -----------------------------------------------------
-- Table `db_smart_traffic_light`.`recordings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_smart_traffic_light`.`recordings` ;

CREATE TABLE IF NOT EXISTS `db_smart_traffic_light`.`recordings` (
  `recording_id` BIGINT NOT NULL AUTO_INCREMENT,
  `rpi_path` VARCHAR(50) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`recording_id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_smart_traffic_light`.`intersections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_smart_traffic_light`.`intersections` ;

CREATE TABLE IF NOT EXISTS `db_smart_traffic_light`.`intersections` (
  `intersection_id` BIGINT NOT NULL AUTO_INCREMENT,
  `avenue_status_1` VARCHAR(20) NULL,
  `avenue_status_2` VARCHAR(20) NULL,
  `number_vehicles` INT NULL,
  `traffic_level` VARCHAR(20) NULL,
  `recording_id` BIGINT NOT NULL,
  PRIMARY KEY (`intersection_id`),
  INDEX `fk_intersections_recordings_idx` (`recording_id` ASC) VISIBLE)
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Ejemplo 1
INSERT INTO `db_smart_traffic_light`.`recordings` (`rpi_path`, `date`)
VALUES ('/path/to/rpi1', '2023-12-01 12:30:00');

-- Ejemplo 2
INSERT INTO `db_smart_traffic_light`.`recordings` (`rpi_path`, `date`)
VALUES ('/path/to/rpi2', '2023-12-02 15:45:30');

-- Ejemplo 3
INSERT INTO `db_smart_traffic_light`.`recordings` (`rpi_path`, `date`)
VALUES ('/path/to/rpi3', '2023-12-03 08:10:15');


-- Ejemplo 1
INSERT INTO `db_smart_traffic_light`.`intersections` 
(`avenue_status_1`, `avenue_status_2`, `number_vehicles`, `traffic_level`, `recording_id`)
VALUES ('Green', 'Red', 20, 'Low', 1);

-- Ejemplo 2
INSERT INTO `db_smart_traffic_light`.`intersections` 
(`avenue_status_1`, `avenue_status_2`, `number_vehicles`, `traffic_level`, `recording_id`)
VALUES ('Red', 'Green', 15, 'Medium', 2);

-- Ejemplo 3
INSERT INTO `db_smart_traffic_light`.`intersections` 
(`avenue_status_1`, `avenue_status_2`, `number_vehicles`, `traffic_level`, `recording_id`)
VALUES ('Yellow', 'Red', 25, 'High', 3);
